#!/usr/bin/env bash
# - Displays numbers from 1..100
# - Displays Fizzbuzz if the number is divisible by 3 and 5
# - Displays Fizz if the number is divisble by 3
# - Displays Buzz if the number is divisible by 5

for i in {1..100}
	do
		if (( $i % 3 == 0 && $i % 5 == 0 ))
			then
				echo "FizzBuzz"
		elif (( $i % 3 == 0 ))
			then
				echo "Fizz"
		elif (( $i % 5 == 0 ))
			then
				echo "Buzz"
		else
			echo "$i"
		fi
	done

